//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class BillItem:INotifyPropertyChanged
    {
        public int Id { get; set; }
        public string NameProduct { get; set; }
        public double PriceProduct { get; set; }
        private double quantityProduct;

        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged([CallerMemberName]string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        public double QuantityProduct
        {
            get { return quantityProduct; }
            set 
            { 
                quantityProduct = value;
                OnPropertyChanged();
            }
        }
        private double totalPrice;

        public double TotalPrice
        {
            get { return totalPrice; }
            set 
            { 
                totalPrice = value;
                OnPropertyChanged();
            }
        }

        public Nullable<int> BillId { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
